# tomcat
server:
  port: 8011
#  servlet:
#    context-path:
#    max-http-header-size: 204800

mybatis:
  mapper-locations: # 所有的mapper映射文件
    - classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射
    call-setters-on-nulls: true

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册到Eureka Server
    service-url:
      defaultZone: http://127.0.0.1:9090/eureka
    registry-fetch-interval-seconds: 180 #此参数会更新路由信息
    instance:
      instance-id: mall-product
spring:
  profiles:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall_sys?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  application:
    name: mall-product
  rabbitmq:
    host: 101.200.225.183
    port: 5672
    username: test
    password: 123456
    virtual-host: /
    listener:
      direct:
        acknowledge-mode:  manual
      simple:
        acknowledge-mode: manual
  activemq:
    broker-url:


