# tomcat
server:
  port: 9090

# eureka
eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000
  client:
    register-with-eureka: false  #表示是否将自己注册到Eureka Server
    fetch-registry: false #表示是否从Eureka Server获取注册信息，默认true
    service-url:
      defaultZone: http://127.0.0.1:9090/eureka/

# spring
spring:
  application:
    name: erureka-server